const menuList = [
    {
        title:'首页',
        key:'/home',
        icon:'home',
    },
    {
        title:'账号管理',
        key:'/accountManage',
        icon:'appstore',
        children:[
            {
                title:'账号信息',
                key:'/accountInfoManage',
                icon:'accountInfoManage',
            },            
            {
                title:'修改密码',
                key:'/accountPassword',
                icon:'accountPassword',
            }
        ]
    },
    {
        title:'权限管理',
        key:'/roleSysManage',
        icon:'appstore',
        children:[
            {
                title:'权限管理',
                key:'/authorityManage',
                icon:'authorityManage',
            },            
            {
                title:'角色管理',
                key:'/roleManage',
                icon:'roleManage',
            }
        ]
    },
    {
        title:'用户管理',
        key:'/userManage',
        icon:'appstore',
    },
    {
        title:'文章管理',
        key:'/articleManage',
        icon:'appstore',
        children:[
            {
                title:'文章状态管理',
                key:'/articleStatusManage',
                icon:'articleStatusManage',
            },            
            {
                title:'文章类型管理',
                key:'/articleTypeManage',
                icon:'articleTypeManage',
            }
        ]
    },
]

export default menuList